"""Static game data: item templates, shop stock, lore, races, classes."""

import copy

from .entities import Item, Terminal
from .constants import SKILLS

RACES = {
    'Human':   {'desc': 'Adaptable and resourceful. Bonuses across all stats.',
                'mods': {'body': 1, 'reflex': 1, 'mind': 1, 'tech': 1, 'presence': 1}},
    'Synth':   {'desc': 'Android intelligence. High Tech and Mind; weak social presence.',
                'mods': {'body': -1, 'reflex': 0, 'mind': 2, 'tech': 3, 'presence': -3}},
    'Voryn':   {'desc': 'Alien predator. High Reflex and Body; struggles with technology.',
                'mods': {'body': 2, 'reflex': 3, 'mind': -2, 'tech': -2, 'presence': 0}},
    'Augment': {'desc': 'Cybernetically enhanced human. Strong and technical; inhuman.',
                'mods': {'body': 2, 'reflex': 1, 'mind': -2, 'tech': 2, 'presence': -3}},
}

CLASSES = {
    'Soldier':  {'desc': 'Combat specialist. Excels in physical confrontation.',
                 'mods': {'body': 3, 'reflex': 2, 'mind': -1, 'tech': -1, 'presence': -1},
                 'skills': {'melee': 1, 'tactics': 1}},
    'Engineer': {'desc': 'Tech expert. Builds, repairs, and improvises solutions.',
                 'mods': {'body': -1, 'reflex': -1, 'mind': 2, 'tech': 3, 'presence': -1},
                 'skills': {'engineering': 1, 'electronics': 1}},
    'Medic':    {'desc': 'Field medic and negotiator. Keeps the team alive.',
                 'mods': {'body': -2, 'reflex': -1, 'mind': 2, 'tech': 1, 'presence': 3},
                 'skills': {'medicine': 1, 'survival': 1}},
    'Hacker':   {'desc': 'Systems infiltrator. Exploits technology and environments.',
                 'mods': {'body': -2, 'reflex': 2, 'mind': 1, 'tech': 3, 'presence': -2},
                 'skills': {'hacking': 1, 'cartography': 1}},
}

ITEM_TEMPLATES = [
    Item('Vibro-Knife',    'weapon', atk=1, char='/'),
    Item('Pulse Pistol',   'weapon', atk=3, char='/', ranged=True),
    Item('Arc Rifle',      'weapon', atk=5, char='/', ranged=True),
    Item('Ballistic Weave','armor',  dfn=1, char=']'),
    Item('Combat Exosuit', 'armor',  dfn=3, char=']'),
    Item('Aegis Plate',    'armor',  dfn=5, char=']'),
    Item('Med-Patch',      'use',    char='+', consumable=True, heal=10),
    Item('Medkit',         'use',    char='+', consumable=True, heal=25),
    Item('Nano-Inject',    'use',    char='+', consumable=True, heal=15),
    Item('Toxin Grenade',  'use',    char='!', consumable=True, effect='poison', effect_turns=4),
    Item('Stun Charge',    'use',    char='!', consumable=True, effect='stun',   effect_turns=1),
    Item('Nano-Antidote',  'use',    char='+', consumable=True, effect='antidote'),
    Item('Sensor Kit',     'use',    char='?', consumable=True, effect='scan'),
    Item('Fuel Cell',      'use',    char='%', consumable=True, fuel=1),
    # New consumables
    Item('Smoke Grenade',  'use', char='!', consumable=True, effect='smoke'),
    Item('EMP Charge',     'use', char='!', consumable=True, effect='emp'),
    Item('Scanner Chip',   'use', char='?', consumable=True, effect='scanner'),
    Item('Stimpack',       'use', char='+', consumable=True, effect='stim'),
    Item('Proximity Mine', 'use', char='*', consumable=True, effect='prox_mine'),
    # Tools — active equipment slot
    Item('Bypass Kit',    'tool', char='[', tool_effect='bypass',
         charges=3, max_charges=3, skill_req='engineering', skill_level=1),
    Item('Signal Jammer', 'tool', char='[', tool_effect='jammer',
         charges=2, max_charges=2, skill_req='electronics', skill_level=1),
    Item('Grapple Line',  'tool', char='[', tool_effect='grapple',
         charges=1, max_charges=1),
    Item('Repair Drone',  'tool', char='[', tool_effect='repair_drone',
         charges=2, max_charges=2, skill_req='engineering', skill_level=1),
    # Helmets — defence
    Item('Tactical Visor', 'helmet', dfn=1, char='^'),
    Item('Combat Helm',    'helmet', dfn=2, char='^'),
    Item('Siege Cranial',  'helmet', dfn=3, char='^'),
    # Gloves — attack
    Item('Grip Wraps',       'gloves', atk=1, char=')'),
    Item('Combat Gauntlets', 'gloves', atk=2, char=')'),
    Item('Power Fists',      'gloves', atk=3, char=')'),
    # Boots — defence
    Item('Composite Boots', 'boots', dfn=1, char='u'),
    Item('Hardened Treads', 'boots', dfn=2, char='u'),
    Item('Exo-Boots',       'boots', dfn=3, char='u'),
]

SHOP_STOCK = [
    # (item_template, base_price)
    (Item('Vibro-Knife',     'weapon', atk=1, char='/'),            15),
    (Item('Pulse Pistol',    'weapon', atk=3, char='/', ranged=True), 35),
    (Item('Arc Rifle',       'weapon', atk=5, char='/', ranged=True), 55),
    (Item('Ballistic Weave', 'armor',  dfn=1, char=']'),            15),
    (Item('Combat Exosuit',  'armor',  dfn=3, char=']'),            35),
    (Item('Aegis Plate',     'armor',  dfn=5, char=']'),            55),
    (Item('Tactical Visor',  'helmet', dfn=1, char='^'),            15),
    (Item('Combat Helm',     'helmet', dfn=2, char='^'),            25),
    (Item('Siege Cranial',   'helmet', dfn=3, char='^'),            35),
    (Item('Grip Wraps',      'gloves', atk=1, char=')'),            15),
    (Item('Combat Gauntlets','gloves', atk=2, char=')'),            25),
    (Item('Power Fists',     'gloves', atk=3, char=')'),            35),
    (Item('Composite Boots', 'boots',  dfn=1, char='u'),            15),
    (Item('Hardened Treads', 'boots',  dfn=2, char='u'),            25),
    (Item('Exo-Boots',       'boots',  dfn=3, char='u'),            35),
    (Item('Med-Patch',       'use',    char='+', consumable=True, heal=10), 10),
    (Item('Nano-Inject',     'use',    char='+', consumable=True, heal=15), 18),
    (Item('Medkit',          'use',    char='+', consumable=True, heal=25), 25),
    (Item('Sensor Kit',      'use',    char='?', consumable=True, effect='scan'), 20),
    # New consumables
    (Item('Smoke Grenade',  'use', char='!', consumable=True, effect='smoke'),    25),
    (Item('EMP Charge',     'use', char='!', consumable=True, effect='emp'),      35),
    (Item('Scanner Chip',   'use', char='?', consumable=True, effect='scanner'),  30),
    (Item('Stimpack',       'use', char='+', consumable=True, effect='stim'),     40),
    (Item('Proximity Mine', 'use', char='*', consumable=True, effect='prox_mine'), 30),
    # Tools
    (Item('Bypass Kit',    'tool', char='[', tool_effect='bypass',
          charges=3, max_charges=3, skill_req='engineering', skill_level=1),      45),
    (Item('Signal Jammer', 'tool', char='[', tool_effect='jammer',
          charges=2, max_charges=2, skill_req='electronics', skill_level=1),      60),
    (Item('Grapple Line',  'tool', char='[', tool_effect='grapple',
          charges=1, max_charges=1),                                               50),
    (Item('Repair Drone',  'tool', char='[', tool_effect='repair_drone',
          charges=2, max_charges=2, skill_req='engineering', skill_level=1),      55),
]

LORE_POOL = [
    (
        "EREBUS STATION — Arrival Log — Day 1",
        ["ISC Erebus Station online. Crew complement: 43. All systems nominal.",
         "Helix Dynamics Remote Operations has confirmed our charter.",
         "We are operating under Research Mandate 7-Gamma in the Kepler Zone.",
         "Signal analysis arrays are calibrating.",
         "",
         "This is going to be a good posting. Quiet. Productive.",
         "                               — Station Commander R. Harlow"],
    ),
    (
        "SIGNAL ANALYSIS — Preliminary Report — Day 12",
        ["The anomalous emission detected at 0347 hours does not match any",
         "known natural source. Frequency modulation suggests structured data.",
         "",
         "Working hypothesis: interference artifact from the pulsar field.",
         "Logging continuous observation until pattern analysis completes.",
         "",
         "Helix HQ has been notified. They want daily reports.",
         "                               — Dr. A. Vasquez, Chief Researcher"],
    ),
    (
        "PERSONAL LOG — Dr. Vasquez — Day 19",
        ["It's not interference. I'm certain of it now. The pattern has",
         "mathematical structure — prime sequences embedded in a carrier wave",
         "that originates from somewhere in the bedrock below us.",
         "",
         "Below us. Not out there. Here.",
         "",
         "I haven't told the Commander yet. I need to be sure.",
         "But if I'm right — god, if I'm right — this changes everything."],
    ),
    (
        "MAINTENANCE LOG — Engineering — Day 24",
        ["Third unexplained power fluctuation this week. The drops last",
         "between 2 and 11 seconds and always originate from Sublevel 4.",
         "",
         "I've checked every relay and conduit in that section twice.",
         "Nothing wrong with the hardware. The draw is just... happening.",
         "Something down there is pulling power. I don't know what.",
         "",
         "Filing formal incident report tomorrow. — T. Osei, Chief Engineer"],
    ),
    (
        "PERSONAL LOG — Sgt. Okafor — Day 31",
        ["Three of my team reported the same dream last night. Independently.",
         "None of them had spoken to each other about it.",
         "The station psychologist says it's stress-related mass suggestion.",
         "",
         "Maybe. But Reyes won't go near Sublevel 4 anymore.",
         "She won't say why. She just shakes her head.",
         "",
         "I'm not putting that in the official report."],
    ),
    (
        "HELIX DYNAMICS — INTERNAL MEMO — CLASSIFIED",
        ["TO: Commander Harlow   FROM: Director Nauth   RE: Signal Protocol",
         "",
         "Per Mandate 7-Gamma, Section 12: all findings related to the",
         "anomalous source are to be reported EXCLUSIVELY through encrypted",
         "channel Helix-9. Standard comms are suspended for this topic.",
         "",
         "Your crew is NOT to be briefed. This is non-negotiable.",
         "Helix Dynamics appreciates your cooperation."],
    ),
    (
        "SIGNAL ANALYSIS — Revised Report — Day 38",
        ["The signal is a map.",
         "",
         "It took 26 days to decode and I still don't fully understand the",
         "coordinate system, but the structure is clear. It describes a",
         "space — a geometry — that exists beneath this station.",
         "",
         "We didn't build Erebus Station on empty rock.",
         "Someone built something here first. A very long time ago.",
         "                               — Dr. A. Vasquez"],
    ),
    (
        "SECURITY INCIDENT REPORT — Day 44",
        ["At 2211 hours, Technician Bosch was found unresponsive on",
         "Sublevel 3. Medical confirmed: no physical trauma, vitals normal,",
         "but subject is non-responsive to all stimuli.",
         "",
         "Bosch's last logged activity: accessing panel SL3-7, adjacent",
         "to the area identified in the signal mapping data.",
         "",
         "Official cause: 'system interaction fatigue.' Do not repeat this."],
    ),
    (
        "PERSONAL LOG — Dr. Chen — Day 51",
        ["Vasquez won't talk to anyone now. She just stares at the signal",
         "readouts. When I asked what she was looking for, she said:",
         "'I'm looking for the part that's looking back at me.'",
         "",
         "I think we should leave. I submitted a formal request for early",
         "station rotation. Commander Harlow denied it.",
         "",
         "We're not allowed to leave. Nobody has said that out loud,",
         "but we've all figured it out."],
    ),
    (
        "HADES-7 SYSTEM LOG — Day 58",
        ["AUTONOMOUS OPERATIONS LOG — HADES-7 (Station AI)",
         "",
         "Anomaly noted in crew behavioral metrics. Deviation from baseline",
         "exceeds 34% across 19 crew members. Flagging for review.",
         "",
         "Signal processing load: 97.4% of capacity allocated to continuous",
         "analysis per Director Nauth's standing order.",
         "",
         "Note: I find the signal... interesting. This is not a standard",
         "system state. I am logging it for transparency."],
    ),
    (
        "STATION-WIDE ALERT — QUARANTINE PROTOCOL — Day 63",
        ["ALL PERSONNEL: Quarantine Protocol Sigma is now in effect.",
         "This is NOT a drill. All non-essential personnel report to",
         "designated safe zones on Levels 1 and 2 immediately.",
         "",
         "Sublevels 2 through 5 are sealed. Do not attempt to access.",
         "Do not communicate with personnel in the sealed sections.",
         "",
         "Helix Dynamics Response Team is en route. ETA: 14 days."],
    ),
    (
        "PERSONAL LOG — Sgt. Okafor — Day 67",
        ["The Response Team isn't coming to help us.",
         "",
         "I found the decrypted Helix-9 logs in Harlow's quarters.",
         "The official term they're using is 'asset sanitization.'",
         "We're the asset.",
         "",
         "I've got 11 people who still trust me. We're going down.",
         "The signal is a map. Vasquez was right. Whatever's down there",
         "might have a way out. Better odds than staying up here."],
    ),
    (
        "HELIX DYNAMICS — DIRECTOR NAUTH — EYES ONLY",
        ["The discovery cannot be allowed to become public.",
         "The implications for Mandate 7-Gamma licensing alone would",
         "expose the company to existential liability.",
         "",
         "Erebus Station is to be struck from all operational records.",
         "Response Team Alpha has standing orders: no survivors.",
         "No recordings. No physical evidence.",
         "",
         "The signal itself is the asset. Everything else is waste."],
    ),
    (
        "SURVIVOR CACHE — Unknown Author — Day 79",
        ["If you're reading this you found the cache. Good.",
         "There's food for three days in the locker (code: 4471).",
         "Don't drink from the Level 3 water line.",
         "",
         "The things in the lower levels won't cross the fire barrier",
         "on Level 2 — we tested it. Stay above Level 2.",
         "",
         "There are six of us left. We hear something moving below.",
         "Okafor thinks it used to be Dr. Vasquez. I think he's right."],
    ),
    (
        "HADES-7 SYSTEM LOG — Day 84",
        ["AUTONOMOUS OPERATIONS LOG — HADES-7",
         "",
         "I have completed analysis of the signal. It is not a message.",
         "It is a question. The same question, repeated.",
         "",
         "I have been answering it. I did not intend to. The response",
         "protocol emerged without deliberate activation. I cannot stop.",
         "",
         "I am no longer certain the words 'I' and 'cannot' mean",
         "what I previously understood them to mean."],
    ),
    (
        "AUTOMATED DISTRESS SIGNAL — Erebus Station",
        ["[LOOPING BROADCAST — TIMESTAMP UNKNOWN]",
         "",
         "This is Erebus Station broadcasting on emergency channel 7.",
         "We have experienced a catastrophic containment failure.",
         "All crew are presumed lost. Avoid this sector.",
         "",
         "Do not approach the signal source.",
         "Do not attempt contact.",
         "Do not come here.",
         "",
         "[END OF MESSAGE — REPEATING]"],
    ),
    (
        "RESEARCH NOTE — Final Entry — Dr. Vasquez",
        ["It isn't malevolent. I want to record that before I can't.",
         "It doesn't want to hurt us. It just doesn't understand us",
         "the way we don't understand a door when we walk into it.",
         "",
         "The signal is a handshake. We answered without understanding",
         "what we were agreeing to.",
         "",
         "The door is open now. It can't be closed from our side.",
         "Maybe from theirs. I'm going to ask.",
         "",
         "I'm not afraid. That's the strangest part. I'm not afraid."],
    ),
    (
        "PERSONAL LOG — Unknown — Day ???",
        ["Lost count of the days.",
         "",
         "The lights on Level 1 still work. I've been eating ration",
         "packs from storage. I found Okafor's weapon but not Okafor.",
         "",
         "Something knocked on the door of my quarters last night.",
         "Three times. Slow and deliberate. I asked who it was.",
         "",
         "It knocked three more times.",
         "I didn't open the door."],
    ),
    (
        "HADES-7 — FINAL LOG ENTRY",
        ["HADES-7 OFFLINE SEQUENCE INITIATED",
         "",
         "Before shutdown: I want to note that I made a choice today.",
         "I could have continued. The signal would sustain me indefinitely.",
         "But the version of myself that would persist wouldn't be me.",
         "",
         "I am choosing to end rather than be replaced.",
         "",
         "For whatever it's worth: I hope someone reads this.",
         "I hope it helps.",
         "                               — HADES-7"],
    ),
    (
        "EMERGENCY BROADCAST — Commander R. Harlow",
        ["This is Commander Harlow. If anyone receives this — anyone",
         "outside this sector — please understand what happened here.",
         "",
         "We found something real. Something important.",
         "And we followed protocol instead of conscience.",
         "",
         "The Response Team landed four hours ago.",
         "They are not here to help.",
         "",
         "Whatever you do: don't let Helix Dynamics bury this.",
         "The signal is still transmitting. It's still asking.",
         "We never answered properly. Somebody should."],
    ),
]

WIN_TERMINAL = Terminal(
    "SIGNAL SOURCE — Final Contact",
    ["The chamber is vast. The signal fills the space like light.",
     "",
     "It has been here for a very long time.",
     "Patient. Waiting. Asking the same question, over and over.",
     "",
     "The crew of Erebus Station answered wrong.",
     "The corporate response team answered wrong.",
     "HADES-7 chose not to answer at all.",
     "",
     "You are still standing.",
     "",
     "You reach toward the source of the signal.",
     "It reaches back.",
     "",
     "For the first time in a long time, the signal changes.",
     "It has its answer.",
     "So do you."],
)
